/* Port of regex-syntax 0.7.2 src/unicode_tables/perl_decimal.rs, MIT OR Apache-2.0. Unicode data: Unicode License (LICENSE-UNICODE). */
/* Generated by native/tools/generate_regex_tables.py; do not edit. The Rust source says:
 * DO NOT EDIT THIS FILE. IT WAS AUTOMATICALLY GENERATED BY:
 *
 * ucd-generate general-category ucd-15.0.0 --chars --include decimalnumber
 *
 * Unicode version: 15.0.0.
 *
 * ucd-generate 0.2.14 is available on crates.io.
 *
 * Unicode License (regex-syntax 0.7.2 src/unicode_tables/LICENSE-UNICODE):
 *
 * COPYRIGHT AND PERMISSION NOTICE
 *
 * Copyright © 1991-2018 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Permission is hereby granted, free of charge, to any person obtaining
 * a copy of the Unicode data files and any associated documentation
 * (the "Data Files") or Unicode software and any associated documentation
 * (the "Software") to deal in the Data Files or Software
 * without restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, and/or sell copies of
 * the Data Files or Software, and to permit persons to whom the Data Files
 * or Software are furnished to do so, provided that either
 * (a) this copyright and permission notice appear with all copies
 * of the Data Files or Software, or
 * (b) this copyright and permission notice appear in associated
 * Documentation.
 *
 * THE DATA FILES AND SOFTWARE ARE PROVIDED "AS IS", WITHOUT WARRANTY OF
 * ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT OF THIRD PARTY RIGHTS.
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS
 * NOTICE BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL
 * DAMAGES, OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE,
 * DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
 * TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
 * PERFORMANCE OF THE DATA FILES OR SOFTWARE.
 *
 * Except as contained in this notice, the name of a copyright holder
 * shall not be used in advertising or otherwise to promote the sale,
 * use or other dealings in these Data Files or Software without prior
 * written authorization of the copyright holder.
 */
#include "unicode_tables.h"
/* regex 1.8.4's features compile this table out (see the generator); no data. */
