/* Port of regex-syntax 0.7.2 src/unicode_tables/mod.rs, MIT OR Apache-2.0. Unicode data: Unicode License (LICENSE-UNICODE). */
/* Generated by native/tools/generate_regex_tables.py; do not edit. The C shapes of
 * regex-syntax 0.7.2's Unicode 15.0.0 tables (ucd-generate 0.2.14), private to the regex
 * front end. Every array is sorted as in the Rust source: names in byte order (for
 * binary search), ranges and case folding keys ascending. */
#ifndef CHAINNER_REGEX_UNICODE_TABLES_H
#define CHAINNER_REGEX_UNICODE_TABLES_H
#include "chainner_hir.h"

/* (&'static str, &'static [(char, char)]): a BY_NAME entry. */
typedef struct chn_ut_named_ranges {
    const char *name;
    const chn_hir_class_unicode_range *ranges;
    size_t len;
} chn_ut_named_ranges;

/* (&'static str, &'static str): a normalized alias and its canonical name. */
typedef struct chn_ut_name_pair {
    const char *name;
    const char *canonical;
} chn_ut_name_pair;

/* (&'static str, &'static [(&'static str, &'static str)]): a PROPERTY_VALUES entry. */
typedef struct chn_ut_property_value_set {
    const char *property;
    const chn_ut_name_pair *values;
    size_t len;
} chn_ut_property_value_set;

/* (char, &'static [char]): a CASE_FOLDING_SIMPLE entry; its slice is
 * chn_ut_case_folding_simple_values[offset .. offset + len]. */
typedef struct chn_ut_case_fold {
    uint32_t c;
    uint32_t offset;
    uint32_t len;
} chn_ut_case_fold;

/* age::BY_NAME */
extern const chn_ut_named_ranges chn_ut_age_by_name[];
extern const size_t chn_ut_age_by_name_len;

/* general_category::BY_NAME */
extern const chn_ut_named_ranges chn_ut_general_category_by_name[];
extern const size_t chn_ut_general_category_by_name_len;

/* grapheme_cluster_break::BY_NAME */
extern const chn_ut_named_ranges chn_ut_grapheme_cluster_break_by_name[];
extern const size_t chn_ut_grapheme_cluster_break_by_name_len;

/* property_bool::BY_NAME */
extern const chn_ut_named_ranges chn_ut_property_bool_by_name[];
extern const size_t chn_ut_property_bool_by_name_len;

/* script::BY_NAME */
extern const chn_ut_named_ranges chn_ut_script_by_name[];
extern const size_t chn_ut_script_by_name_len;

/* script_extension::BY_NAME */
extern const chn_ut_named_ranges chn_ut_script_extension_by_name[];
extern const size_t chn_ut_script_extension_by_name_len;

/* sentence_break::BY_NAME */
extern const chn_ut_named_ranges chn_ut_sentence_break_by_name[];
extern const size_t chn_ut_sentence_break_by_name_len;

/* word_break::BY_NAME */
extern const chn_ut_named_ranges chn_ut_word_break_by_name[];
extern const size_t chn_ut_word_break_by_name_len;

/* case_folding_simple::CASE_FOLDING_SIMPLE */
extern const chn_ut_case_fold chn_ut_case_folding_simple[];
extern const size_t chn_ut_case_folding_simple_len;
extern const uint32_t chn_ut_case_folding_simple_values[];

/* perl_word::PERL_WORD */
extern const chn_hir_class_unicode_range *const chn_ut_perl_word;
extern const size_t chn_ut_perl_word_len;

/* property_names::PROPERTY_NAMES */
extern const chn_ut_name_pair chn_ut_property_names[];
extern const size_t chn_ut_property_names_len;

/* property_values::PROPERTY_VALUES */
extern const chn_ut_property_value_set chn_ut_property_values[];
extern const size_t chn_ut_property_values_len;

#endif
