# Minimal type stubs for the parts of cuda-python's runtime API that chaiNNer uses.
# cuda.bindings.runtime is a compiled extension without type information.

from enum import IntEnum

class cudaError_t(IntEnum):
    cudaSuccess = 0

class cudaMemcpyKind(IntEnum):
    cudaMemcpyHostToHost = 0
    cudaMemcpyHostToDevice = 1
    cudaMemcpyDeviceToHost = 2
    cudaMemcpyDeviceToDevice = 3
    cudaMemcpyDefault = 4

class cudaStream_t:
    def __int__(self) -> int: ...

class cudaEvent_t:
    def __int__(self) -> int: ...

class cudaGraph_t:
    def __int__(self) -> int: ...

class cudaGraphExec_t:
    def __int__(self) -> int: ...

class cudaStreamCaptureMode(IntEnum):
    cudaStreamCaptureModeGlobal = 0
    cudaStreamCaptureModeThreadLocal = 1
    cudaStreamCaptureModeRelaxed = 2

class cudaDeviceProp:
    name: bytes
    major: int
    minor: int

cudaEventDisableTiming: int

def cudaGetErrorName(error: cudaError_t) -> tuple[cudaError_t, bytes]: ...
def cudaGetErrorString(error: cudaError_t) -> tuple[cudaError_t, bytes]: ...
def cudaSetDevice(device: int) -> tuple[cudaError_t]: ...
def cudaGetDevice() -> tuple[cudaError_t, int]: ...
def cudaGetDeviceProperties(device: int) -> tuple[cudaError_t, cudaDeviceProp]: ...
def cudaMemGetInfo() -> tuple[cudaError_t, int, int]: ...
def cudaMalloc(size: int) -> tuple[cudaError_t, int]: ...
def cudaFree(dev_ptr: int) -> tuple[cudaError_t]: ...
def cudaMallocHost(size: int) -> tuple[cudaError_t, int]: ...
def cudaFreeHost(ptr: int) -> tuple[cudaError_t]: ...
def cudaStreamCreate() -> tuple[cudaError_t, cudaStream_t]: ...
def cudaStreamSynchronize(stream: cudaStream_t) -> tuple[cudaError_t]: ...
def cudaStreamDestroy(stream: cudaStream_t) -> tuple[cudaError_t]: ...
def cudaEventCreateWithFlags(flags: int) -> tuple[cudaError_t, cudaEvent_t]: ...
def cudaEventRecord(event: cudaEvent_t, stream: cudaStream_t) -> tuple[cudaError_t]: ...
def cudaEventSynchronize(event: cudaEvent_t) -> tuple[cudaError_t]: ...
def cudaEventDestroy(event: cudaEvent_t) -> tuple[cudaError_t]: ...
def cudaMemcpyAsync(
    dst: int, src: int, count: int, kind: cudaMemcpyKind, stream: cudaStream_t
) -> tuple[cudaError_t]: ...
def cudaStreamBeginCapture(
    stream: cudaStream_t, mode: cudaStreamCaptureMode
) -> tuple[cudaError_t]: ...
def cudaStreamEndCapture(stream: cudaStream_t) -> tuple[cudaError_t, cudaGraph_t]: ...
def cudaGraphInstantiate(
    graph: cudaGraph_t, flags: int
) -> tuple[cudaError_t, cudaGraphExec_t]: ...
def cudaGraphLaunch(
    graph_exec: cudaGraphExec_t, stream: cudaStream_t
) -> tuple[cudaError_t]: ...
def cudaGraphExecDestroy(graph_exec: cudaGraphExec_t) -> tuple[cudaError_t]: ...
def cudaGraphDestroy(graph: cudaGraph_t) -> tuple[cudaError_t]: ...
