# Minimal type stubs for the parts of the TensorRT Python API that chaiNNer uses.
# TensorRT ships compiled bindings without type information.

from collections.abc import Iterator, Sequence
from enum import Enum, IntEnum

__version__: str

class DataType(Enum):
    FLOAT = ...
    HALF = ...
    BF16 = ...
    INT8 = ...
    INT32 = ...
    BOOL = ...
    UINT8 = ...
    FP8 = ...
    INT64 = ...

class TensorIOMode(Enum):
    NONE = ...
    INPUT = ...
    OUTPUT = ...

class ExecutionContextAllocationStrategy(Enum):
    STATIC = ...
    ON_PROFILE_CHANGE = ...
    USER_MANAGED = ...

class BuilderFlag(Enum):
    FP16 = ...
    BF16 = ...
    TF32 = ...

class NetworkDefinitionCreationFlag(IntEnum):
    EXPLICIT_BATCH = 0
    STRONGLY_TYPED = 1

class MemoryPoolType(Enum):
    WORKSPACE = ...

class ProfilingVerbosity(Enum):
    LAYER_NAMES_ONLY = ...
    NONE = ...
    DETAILED = ...

class Dims:
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> int: ...
    def __iter__(self) -> Iterator[int]: ...

_Shape = Dims | Sequence[int]

class ILogger:
    class Severity(Enum):
        INTERNAL_ERROR = ...
        ERROR = ...
        WARNING = ...
        INFO = ...
        VERBOSE = ...

class Logger(ILogger):
    INTERNAL_ERROR: ILogger.Severity
    ERROR: ILogger.Severity
    WARNING: ILogger.Severity
    INFO: ILogger.Severity
    VERBOSE: ILogger.Severity
    def __init__(self, min_severity: ILogger.Severity = ...) -> None: ...

def init_libnvinfer_plugins(logger: ILogger | None, namespace: str) -> bool: ...

class IPluginRegistry:
    def load_library(self, plugin_path: str) -> object | None: ...

def get_plugin_registry() -> IPluginRegistry: ...
def nptype(trt_type: DataType) -> type: ...

class IHostMemory:
    def __buffer__(self, flags: int, /) -> memoryview: ...

class IExecutionContext:
    def set_input_shape(self, name: str, shape: _Shape) -> bool: ...
    def get_tensor_shape(self, name: str) -> Dims: ...
    def set_tensor_address(self, name: str, memory: int) -> bool: ...
    def execute_async_v3(self, stream_handle: int) -> bool: ...
    def update_device_memory_size_for_shapes(self) -> int: ...
    def set_device_memory(self, memory: int, size: int) -> None: ...

class ICudaEngine:
    num_io_tensors: int
    def get_tensor_name(self, index: int) -> str: ...
    def get_tensor_mode(self, name: str) -> TensorIOMode: ...
    def get_tensor_shape(self, name: str) -> Dims: ...
    def get_tensor_dtype(self, name: str) -> DataType: ...
    def get_tensor_profile_shape(self, name: str, profile_index: int) -> list[Dims]: ...
    def create_execution_context(
        self, strategy: ExecutionContextAllocationStrategy = ...
    ) -> IExecutionContext | None: ...
    def serialize(self) -> IHostMemory: ...

class Runtime:
    def __init__(self, logger: ILogger) -> None: ...
    def deserialize_cuda_engine(
        self, serialized_engine: bytes
    ) -> ICudaEngine | None: ...

class ITensor:
    name: str
    shape: Dims
    dtype: DataType

class INetworkDefinition:
    num_inputs: int
    num_outputs: int
    def get_input(self, index: int) -> ITensor: ...
    def get_output(self, index: int) -> ITensor: ...

class IOptimizationProfile:
    def set_shape(self, input: str, min: _Shape, opt: _Shape, max: _Shape) -> None: ...

class ITimingCache:
    def serialize(self) -> IHostMemory: ...

class IBuilderConfig:
    builder_optimization_level: int
    max_aux_streams: int
    profiling_verbosity: ProfilingVerbosity
    plugins_to_serialize: list[str]
    def set_memory_pool_limit(self, pool: MemoryPoolType, pool_size: int) -> None: ...
    def set_flag(self, flag: BuilderFlag) -> None: ...
    def clear_flag(self, flag: BuilderFlag) -> None: ...
    def add_optimization_profile(self, profile: IOptimizationProfile) -> int: ...
    def create_timing_cache(self, serialized_timing_cache: bytes) -> ITimingCache: ...
    def set_timing_cache(self, cache: ITimingCache, ignore_mismatch: bool) -> bool: ...
    def get_timing_cache(self) -> ITimingCache | None: ...

class Builder:
    def __init__(self, logger: ILogger) -> None: ...
    def create_network(self, flags: int = 0) -> INetworkDefinition: ...
    def create_builder_config(self) -> IBuilderConfig: ...
    def create_optimization_profile(self) -> IOptimizationProfile: ...
    def build_serialized_network(
        self, network: INetworkDefinition, config: IBuilderConfig
    ) -> IHostMemory | None: ...

class ParserError:
    def desc(self) -> str: ...

class OnnxParser:
    num_errors: int
    def __init__(self, network: INetworkDefinition, logger: ILogger) -> None: ...
    def parse(self, model: bytes, path: str | None = None) -> bool: ...
    def parse_from_file(self, model: str) -> bool: ...
    def get_error(self, index: int) -> ParserError: ...
