# Partial type stub for ncnn.ncnn, the compiled module of the PyPI ncnn wheel
# (ncnn 1.0.20260526). It declares only what backend/src and native/tests use, typed
# from the module's pybind11 signatures; members the wheel lacks are never declared.
# Extend it when the backend or the tests use more of ncnn.

from collections.abc import Buffer, Sequence
from typing import ClassVar, SupportsFloat, SupportsIndex, SupportsInt, TypeAlias

_Int: TypeAlias = SupportsInt | SupportsIndex
_Float: TypeAlias = SupportsFloat | SupportsIndex

def get_gpu_count() -> int: ...
def destroy_gpu_instance() -> None: ...
def get_gpu_info(device_index: _Int = 0) -> GpuInfo: ...
def get_gpu_device(device_index: _Int = 0) -> VulkanDevice: ...

class GpuInfo:
    def device_name(self) -> str: ...

class VulkanDevice:
    def acquire_blob_allocator(self) -> VkAllocator: ...
    def acquire_staging_allocator(self) -> VkAllocator: ...
    def get_heap_budget(self) -> int: ...

class VkAllocator: ...

class VkBlobAllocator(VkAllocator):
    def __init__(self, arg0: VulkanDevice, /) -> None: ...
    def clear(self) -> None: ...

class VkStagingAllocator(VkAllocator):
    def __init__(self, arg0: VulkanDevice, /) -> None: ...
    def clear(self) -> None: ...

class Mat:
    class PixelType:
        PIXEL_RGB: ClassVar[Mat.PixelType]
        PIXEL_GRAY: ClassVar[Mat.PixelType]
        PIXEL_RGBA: ClassVar[Mat.PixelType]
        def __int__(self) -> int: ...

    def __init__(self, array: Buffer) -> None: ...
    def __buffer__(self, flags: int, /) -> memoryview: ...
    def clone(self) -> Mat: ...
    @staticmethod
    def from_pixels(array: Buffer, type: _Int, w: _Int, h: _Int) -> Mat: ...
    def substract_mean_normalize(
        self, mean: Sequence[_Float], norm: Sequence[_Float]
    ) -> None: ...

class Option:
    use_fp16_packed: bool
    use_fp16_storage: bool
    use_fp16_arithmetic: bool
    use_vulkan_compute: bool
    use_winograd_convolution: bool
    use_sgemm_convolution: bool
    num_threads: int
    openmp_blocktime: int
    blob_vkallocator: VkAllocator | None
    workspace_vkallocator: VkAllocator | None
    staging_vkallocator: VkAllocator | None

class Extractor:
    # The bound parameter is named `in`, a keyword, so it is positional-only here.
    def input(self, blob_name: str, mat: Mat, /) -> int: ...
    def extract(self, blob_name: str, type: _Int = 0) -> tuple[int, Mat]: ...

class Net:
    opt: Option
    def __init__(self) -> None: ...
    def create_extractor(self) -> Extractor: ...
    def set_vulkan_device(self, device_index: _Int) -> None: ...
    def load_param_mem(self, mem: str) -> int: ...
    # pybind11's string caster takes bytes as well as str.
    def load_model_mem(self, mem: str | bytes) -> None: ...
    def load_model(self, modelpath: str) -> int: ...
